# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:
    movies_upload_dir: '%kernel.project_dir%/public/uploads/images'
    brevo.sender_email: '%env(BREVO_SENDER_EMAIL)%'
    brevo.sender_name: '%env(BREVO_SENDER_NAME)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        # BINDINGS - This tells Symfony what values to inject for these string parameters
        bind:
            string $senderEmail: '%brevo.sender_email%'
            string $senderName: '%brevo.sender_name%'

    # No need to explicitly define services anymore - bindings will handle them
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']